language: node_js
node_js:
 - "0.8"
services: 
 - mongodb
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - npm install -g forever
 - forever start app.js
 - sleep 5
script:
 - testacular start config/testacular.conf.js
after_script:
 - forever stopall